requires "Kossy", 0.19;
requires "DBIx::Sunny";
requires "JSON::XS";
requires "Digest::SHA";
requires "File::Temp";
requires "Time::Piece";
requires "Text::Markdown::Discount";

requires "DBD::mysql";
requires "Starlet";
requires "Plack::Session";
requires "Cache::Memcached::Fast";
requires "Plack::Middleware::AxsLog";
